Repository intuitem/ciso-assistant-community, pull requests merged in 2024-12, with the labels that each got.

#1075 Make language choice persistent for users
  .github/workflows/functional-tests.yml
  .github/workflows/startup-tests.yml
  backend/ciso_assistant/settings.py
  backend/core/urls.py
  backend/core/views.py
  backend/iam/migrations/0009_create_allauth_emailaddress_objects.py
  backend/iam/migrations/0010_user_preferences.py
  backend/iam/models.py
  backend/iam/views.py
  enterprise/frontend/src/routes/+layout.svelte
  frontend/src/lib/components/SideBar/SideBarFooter.svelte
  frontend/src/routes/(app)/+page.server.ts
  frontend/src/routes/(authentication)/login/+page.server.ts
  frontend/src/routes/+layout.svelte
  frontend/src/routes/api/user-preferences/+server.ts
  frontend/tests/functional/startup.test.ts
  frontend/tests/utils/base-page.ts
Labels: data-model

#1187 CNIL : guide sécurité des données
  backend/library/libraries/cnil-guide-securite.yaml
  tools/cnil/cnil-guide-securite.xlsx
Labels: Framework

#1206 Model/add strategic scenario
  backend/core/base_models.py
  backend/core/startup.py
  backend/ebios_rm/migrations/0008_remove_attackpath_ro_to_couple_strategicscenario_and_more.py
  backend/ebios_rm/models.py
  backend/ebios_rm/serializers.py
  backend/ebios_rm/urls.py
  backend/ebios_rm/views.py
  enterprise/backend/enterprise_core/settings.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/CommandPalette/paletteData.ts
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/AttackPathForm.svelte
  frontend/src/lib/components/Forms/ModelForm/OperationalScenarioForm.svelte
  frontend/src/lib/components/Forms/ModelForm/StrategicScenarioForm.svelte
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/load.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/workshop-1/ebios-rm-study/+page.svelte
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/workshop-3/strategic-scenarios/+page.server.ts
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/workshop-4/operational-scenario/+page.server.ts
  frontend/src/routes/(app)/(internal)/operational-scenarios/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/ro-to/[id=uuid]/+page.svelte
Labels: data-model

#1236 Feat/disable steps ebios
  backend/ebios_rm/models.py
  backend/ebios_rm/serializers.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/Tile.svelte
Labels: UX

#1235 Specify label for EBIOS RM tile links
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/Tile.svelte
Labels: UX

#1239 Add redirect URL to risk scenario edit form action
  frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/edit/+page.svelte
Labels: UX

#1238 Integrate new breadcrumbs with command palette
  frontend/src/lib/components/CommandPalette/CommandPalette.svelte
Labels: UX

#1237 Run invalidateAll on EBIOS RM workshop state change
  frontend/src/routes/(app)/(internal)/ebios-rm/[id=uuid]/Tile.svelte
Labels: UX

#1250 Fix flash mode and table mode shortcuts interfering with inputs
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/+page.svelte
Labels: bug
