Repository intuitem/ciso-assistant-community, pull requests merged in 2025-05, with the labels that each got.

#1900 feat: sync requirement assessment to applied controls status
  backend/core/models.py
  backend/core/views.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/+page.server.ts
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/sync-to-actions/+server.ts
  research/scf_db/.lock
  research/scf_db/.shadow
  research/scf_db/.wal
  research/scf_db/catalog.kz
  research/scf_db/data.kz
  research/scf_db/metadata.kz
Labels: High Value

#1874 feat: feature flags management
  backend/global_settings/migrations/0003_alter_globalsettings_name.py
  backend/global_settings/models.py
  backend/global_settings/serializers.py
  backend/global_settings/urls.py
  backend/global_settings/views.py
  enterprise/frontend/src/lib/components/SideBar/navData.ts
  enterprise/frontend/src/lib/feature-flags.ts
  enterprise/frontend/src/routes/(app)/(internal)/settings/+page.svelte
  enterprise/frontend/src/routes/(app)/+layout.svelte
  frontend/messages/en.json
  frontend/src/hooks.server.ts
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/FeatureFlagsSettingForm.svelte
  frontend/src/lib/components/SideBar/SideBar.svelte
  frontend/src/lib/components/SideBar/SideBarItem.svelte
  frontend/src/lib/components/SideBar/SideBarNavigation.svelte
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/lib/feature-flags.ts
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/sidebar-config.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/settings/+page.server.ts
  frontend/src/routes/(app)/(internal)/settings/+page.svelte
  frontend/src/routes/(app)/+layout.server.ts
  frontend/src/routes/(app)/+layout.svelte
Labels: High Value, data-model

#1944 feat: context menu for quicker actions
  frontend/messages/en.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/lib/components/ContextMenu/applied-controls/ChangeStatus.svelte
  frontend/src/lib/components/ModelTable/ModelTable.svelte
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/table.ts
  frontend/src/params/fields.ts
  frontend/src/routes/(app)/(internal)/[model=urlmodel]/[id=uuid]/[field=fields]/+server.ts
Labels: ux

#1940 feat: business impact analysis (bia)
  backend/ciso_assistant/settings.py
  backend/core/startup.py
  backend/core/urls.py
  backend/resilience/__init__.py
  backend/resilience/admin.py
  backend/resilience/apps.py
  backend/resilience/migrations/0001_initial.py
  backend/resilience/migrations/__init__.py
  backend/resilience/models.py
  backend/resilience/serializers.py
  backend/resilience/tests.py
  backend/resilience/urls.py
  backend/resilience/views.py
  enterprise/backend/enterprise_core/settings.py
  enterprise/frontend/src/lib/components/SideBar/navData.ts
  enterprise/frontend/src/routes/(app)/(internal)/domain-analytics/details/[id=uuid]/+page.svelte
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/DataViz/ActivityTracker.svelte
  frontend/src/lib/components/DataViz/LineHeatmap.svelte
  frontend/src/lib/components/Forms/Duration.svelte
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/AssetAssessmentForm.svelte
  frontend/src/lib/components/Forms/ModelForm/BusinessImpactAnalysisForm.svelte
  frontend/src/lib/components/Forms/ModelForm/EscalationThresholdForm.svelte
  frontend/src/lib/components/SideBar/SideBarItem.svelte
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/load.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/asset-assessments/[id=uuid]/+page.server.ts
  frontend/src/routes/(app)/(internal)/asset-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/asset-assessments/[id=uuid]/action-plan/+page.server.ts
  frontend/src/routes/(app)/(internal)/asset-assessments/[id=uuid]/action-plan/+page.svelte
  frontend/src/routes/(app)/(internal)/business-impact-analysis/[id=uuid]/+page.server.ts
  frontend/src/routes/(app)/(internal)/business-impact-analysis/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/business-impact-analysis/[id=uuid]/action-plan/+page.server.ts
  frontend/src/routes/(app)/(internal)/business-impact-analysis/[id=uuid]/action-plan/+page.svelte
  frontend/src/routes/(app)/(internal)/business-impact-analysis/[id=uuid]/visual/+page.server.ts
  frontend/src/routes/(app)/(internal)/business-impact-analysis/[id=uuid]/visual/+page.svelte
  frontend/src/routes/(app)/(internal)/experimental/data-wizard/+page.server.ts
  frontend/src/routes/(app)/(internal)/my-assignments/+page.svelte
  frontend/tests/functional/user-route.test.ts
Labels: High Value, data-model

#1961 feat: support asset classes
  backend/core/migrations/0072_assetclass_asset_asset_class_and_more.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/startup.py
  backend/core/urls.py
  backend/core/views.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm/AssetForm.svelte
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/i18n.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
Labels: data-model

#1978 fix(toolbox): prepare_mapping.py file reading encoding enforces UTF-8
  tools/prepare_mapping.py
Labels: bugfix

#1981 feat: 5-levels scale for security objectives
  backend/core/migrations/0073_alter_asset_security_objectives.py
  backend/core/models.py
  backend/global_settings/views.py
  documentation/architecture/data-model.md
  frontend/src/lib/utils/constants.ts
Labels: data-model

#1938 feat: performance improvement for library update
  backend/core/models.py
Labels: perf

#1999 feat: add reporting timestamp and detection channel to incidents
  backend/core/migrations/0075_incident_detection_incident_reported_at.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/views.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm/IncidentForm.svelte
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
Labels: data-model

#1997 feat: eta and due date in findings
  backend/core/migrations/0076_finding_due_date_finding_eta.py
  backend/core/models.py
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm/FindingForm.svelte
  frontend/src/lib/utils/schemas.ts
Labels: data-model

#2023 fix: broken action plan search bar
  backend/core/views.py
Labels: bugfix

#2024 feat: add external link to incident
  backend/core/migrations/0077_incident_link.py
  backend/core/models.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/Forms/ModelForm/IncidentForm.svelte
  frontend/src/lib/utils/schemas.ts
Labels: data-model

#2013 fix: filters inconsistency with url params after redirections
  frontend/src/lib/components/ModelTable/ModelTable.svelte
Labels: ui, bugfix

#2001 feat(lib): NIST SP-800-66 Rev.2 Restructuring
  backend/library/libraries/nist-sp-800-66-rev2.yaml
  tools/nist/sp-800-66/nist-sp-800-66-rev2.xlsx
  tools/nist/sp-800-66/nist-sp-800-66.py
  tools/nist/sp-800-66/requirement_numbering.py
Labels: Framework

#2059 feat(lib): VCSA v1.1 Framework
  backend/library/libraries/vcsa-v1.1.yaml
  tools/excel/vcsa/ENX_VCSA_1_1_EN.xlsx
  tools/excel/vcsa/convert_vcsa-v1.1.py
  tools/excel/vcsa/vcsa-v1.1.xlsx
  tools/excel/vcsa/vcsa-v1.1_new.xlsx
Labels: Framework
