Repository intuitem/ciso-assistant-community, pull requests merged in 2025-01, with the labels that each got.

#1295 Indonesian translation
  backend/ciso_assistant/settings.py
  frontend/messages/ar.json
  frontend/messages/cs.json
  frontend/messages/de.json
  frontend/messages/en.json
  frontend/messages/es.json
  frontend/messages/fr.json
  frontend/messages/hi.json
  frontend/messages/id.json
  frontend/messages/it.json
  frontend/messages/nl.json
  frontend/messages/pl.json
  frontend/messages/pt.json
  frontend/messages/ro.json
  frontend/messages/sv.json
  frontend/messages/ur.json
  frontend/project.inlang/settings.json
  frontend/src/lib/components/SideBar/SideBarFooter.svelte
  frontend/src/lib/utils/locales.ts
Labels: translation

#1292 Add OWASP's checklist for LLM governance
  backend/library/libraries/owasp-llm-checklist.yaml
  tools/owasp/owasp-llm-checklist.xlsx
Labels: Framework

#1294 Spanish translation for NIS2 2024/2690 annex
  backend/library/libraries/annex-implementing-regulation-of-nis2-on-t-m.yaml
Labels: Framework

#1303 NIS2 Translation to Spanish
  tools/NIS2/nis2-directive.xlsx
Labels: Framework

#1309 NIS2 Spanish translation yaml
  backend/library/libraries/nis2-directive.yaml
Labels: Framework

#1339 Add documentation score
  .github/workflows/backend-linters.yaml
  backend/core/helpers.py
  backend/core/migrations/0049_complianceassessment_show_documentation_score_and_more.py
  backend/core/models.py
  backend/core/views.py
  frontend/messages/ar.json
  frontend/messages/cs.json
  frontend/messages/de.json
  frontend/messages/en.json
  frontend/messages/es.json
  frontend/messages/fr.json
  frontend/messages/hi.json
  frontend/messages/id.json
  frontend/messages/it.json
  frontend/messages/nl.json
  frontend/messages/pl.json
  frontend/messages/pt.json
  frontend/messages/ro.json
  frontend/messages/sv.json
  frontend/messages/ur.json
  frontend/src/lib/components/Forms/Checkbox.svelte
  frontend/src/lib/components/Forms/ModelForm/ComplianceAssessmentForm.svelte
  frontend/src/lib/components/Forms/ModelForm/EntityAssessmentForm.svelte
  frontend/src/lib/components/Forms/ModelForm/SolutionForm.svelte
  frontend/src/lib/components/Forms/Score.svelte
  frontend/src/lib/utils/helpers.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/TreeViewItemContent.svelte
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/TreeViewItemLead.svelte
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.server.ts
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/table-mode/+page.svelte
  frontend/src/routes/(app)/(third-party)/requirement-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(third-party)/requirement-assessments/[id=uuid]/edit/+page.svelte
Labels: data-model

#1376 export/import domain
  backend/core/models.py
  backend/core/serializer_fields.py
  backend/core/serializers.py
  backend/core/templates/snippets/req_node.html
  backend/core/tests/fixtures.py
  backend/core/tests/test_vulnerability.py
  backend/core/views.py
  backend/ebios_rm/serializers.py
  backend/library/serializers.py
  backend/serdes/serializers.py
  backend/serdes/utils.py
  backend/tprm/serializers.py
  enterprise/frontend/src/lib/components/Forms/ModelForm/FolderForm.svelte
  enterprise/frontend/src/routes/(app)/(internal)/folders/[id=uuid]/+page.server.ts
  enterprise/frontend/src/routes/(app)/(internal)/folders/[id=uuid]/+page.svelte
  enterprise/frontend/src/routes/(app)/(internal)/folders/[id=uuid]/export/+server.ts
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/FolderForm.svelte
  frontend/src/lib/components/Modals/CreateModal.svelte
  frontend/src/lib/utils/actions.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/routes/(app)/(internal)/[model=urlmodel]/+page.server.ts
  frontend/src/routes/(app)/(internal)/[model=urlmodel]/+page.svelte
Labels: High Value

#1333 Guided tour: experiment
  .gitignore
  backend/ciso_assistant/settings.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/lib/components/Forms/TextField.svelte
  frontend/src/lib/components/ModelTable/LibraryActions.svelte
  frontend/src/lib/components/ModelTable/ModelTable.svelte
  frontend/src/lib/components/ModelTable/Search.svelte
  frontend/src/lib/components/SideBar/SideBar.svelte
  frontend/src/lib/components/SideBar/SideBarFooter.svelte
  frontend/src/lib/components/SideBar/SideBarItem.svelte
  frontend/src/lib/components/SideBar/SideBarNavigation.svelte
  frontend/src/lib/utils/stores.ts
  frontend/src/routes/(app)/(internal)/[model=urlmodel]/+page.svelte
  frontend/src/routes/(app)/(third-party)/[model=thirdparty_urlmodels]/+page.svelte
Labels: High Value

#1224 build: new production ready helm chart
  .gitignore
  charts/ciso-assistant-next/.helmignore
  charts/ciso-assistant-next/Chart.lock
  charts/ciso-assistant-next/Chart.yaml
  charts/ciso-assistant-next/README.md
  charts/ciso-assistant-next/README.md.gotmpl
  charts/ciso-assistant-next/templates/_helpers.tpl
  charts/ciso-assistant-next/templates/backend/deployment.yaml
  charts/ciso-assistant-next/templates/backend/persistentvolumeclaim.yaml
  charts/ciso-assistant-next/templates/backend/secret.yaml
  charts/ciso-assistant-next/templates/backend/service.yaml
  charts/ciso-assistant-next/templates/frontend/deployment.yaml
  charts/ciso-assistant-next/templates/frontend/service.yaml
  charts/ciso-assistant-next/templates/ingress/ingress.yaml
  charts/ciso-assistant-next/templates/ingress/tls-secret.yaml
  charts/ciso-assistant-next/values.yaml
Labels: deployment

#1444 refactor!: move compliance overview to a dedicated recap page
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/routes/(app)/(internal)/analytics/+page.server.ts
  frontend/src/routes/(app)/(internal)/analytics/+page.svelte
  frontend/src/routes/(app)/(internal)/recap/+layout.svelte
  frontend/src/routes/(app)/(internal)/recap/+page.server.ts
  frontend/src/routes/(app)/(internal)/recap/+page.svelte
Labels: perf
