Repository intuitem/ciso-assistant-community, pull requests merged in 2025-08, with the labels that each got.

#2307 Translation tr
  frontend/messages/tr.json
Labels: i18n

#2304 test: my assignments page
  frontend/tests/functional/detailed/my-assignments.test.ts
  frontend/tests/utils/test-utils.ts
Labels: tests

#2389 feat: add findings trackers and individual findings to my assignements
  frontend/src/routes/(app)/(internal)/my-assignments/+page.svelte
Labels: ui

#2383 chores(perf): load x-rays page in non-blocking mode
  frontend/src/routes/(app)/(internal)/x-rays/+page.server.ts
  frontend/src/routes/(app)/(internal)/x-rays/+page.svelte
Labels: performance

#2382 feat: be able to see all the applied controls attached to a reference control on its details section
  backend/core/views.py
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/table.ts
Labels: ui

#2397 feat: filter country choices by name
  backend/core/constants.py
  backend/privacy/migrations/0005_alter_datacontractor_country_and_more.py
Labels: db-migration

#2385 test: SSO module functional tests
  .github/actions/start-keycloak/action.yml
  .github/workflows/functional-tests.yml
  frontend/tests/.frontend_hash.enterprise
  frontend/tests/e2e-tests.sh
  frontend/tests/functional/detailed/settings/sso.test.ts
  frontend/tests/keycloak/test-realm.json
  frontend/tests/utils/test-utils.ts
Labels: tests

#2409 feat: set first input focus on create modals
  frontend/src/lib/components/Modals/CreateModal.svelte
Labels: ux

#2420 feat: improve audit logs appearance
  enterprise/frontend/src/routes/(app)/(internal)/audit-log/[id]/components/LogEntryChange.svelte
  enterprise/frontend/src/routes/(app)/(internal)/audit-log/[id]/components/RecursiveLogEntryChanges.svelte
Labels: pro

#2464 feat: terminology model and custom risk origins
  backend/core/migrations/0092_terminology.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/startup.py
  backend/core/urls.py
  backend/core/views.py
  backend/ebios_rm/migrations/0013_add_risk_origin_fk.py
  backend/ebios_rm/migrations/0014_migrate_risk_origin.py
  backend/ebios_rm/migrations/0015_replace_risk_origin.py
  backend/ebios_rm/models.py
  backend/ebios_rm/serializers.py
  backend/ebios_rm/tests/test_ro_to.py
  backend/ebios_rm/views.py
  frontend/.gitignore
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/RoToForm.svelte
  frontend/src/lib/components/Forms/ModelForm/TerminologyForm.svelte
  frontend/src/lib/components/Forms/TranslationField.svelte
  frontend/src/lib/components/Modals/CreateModal.svelte
  frontend/src/lib/components/ModelTable/ModelTable.svelte
  frontend/src/lib/components/SideBar/SideBarFooter.svelte
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/lib/utils/constants.ts
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/locales.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/[model=urlmodel]/[id=uuid]/edit/+page.svelte
  frontend/src/routes/(app)/(internal)/operational-scenarios/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/ro-to/[id=uuid]/+page.svelte
  frontend/tests/.frontend_hash.enterprise
  frontend/tests/functional/detailed/ebios-rm.test.ts
Labels: High Value, db-migration
