Repository intuitem/ciso-assistant-community, pull requests merged in 2025-03, with the labels that each got.

#1587 build: release the helm chart using the GH OCI registry
  .github/workflows/helm-build-and-push-ce.yml
  charts/ciso-assistant-next/Chart.yaml
  charts/ciso-assistant-next/README.md
  charts/ciso-assistant-next/README.md.gotmpl
Labels: deployment

#1645 feat: experimental data import wizard
  backend/core/serializers.py
  backend/core/urls.py
  backend/core/views.py
  backend/data_wizard/__init__.py
  backend/data_wizard/admin.py
  backend/data_wizard/apps.py
  backend/data_wizard/migrations/__init__.py
  backend/data_wizard/models.py
  backend/data_wizard/serializers.py
  backend/data_wizard/tests.py
  backend/data_wizard/urls.py
  backend/data_wizard/views.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/src/routes/(app)/(internal)/experimental/+page.svelte
  frontend/src/routes/(app)/(internal)/experimental/data-wizard/+layout.svelte
  frontend/src/routes/(app)/(internal)/experimental/data-wizard/+page.server.ts
  frontend/src/routes/(app)/(internal)/experimental/data-wizard/+page.svelte
  frontend/src/routes/(app)/(internal)/frameworks/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/frameworks/[id=uuid]/excel-template/+server.ts
Labels: High Value

#1612 feat: auditlog capability on the backend
  backend/ciso_assistant/settings.py
  backend/core/custom_middleware.py
  backend/core/management/commands/prune_auditlog.py
  backend/core/models.py
  backend/core/tasks.py
  backend/ebios_rm/models.py
  backend/iam/models.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tprm/models.py
  enterprise/backend/enterprise_core/settings.py
Labels: High Value

#1700 chore: inlang/paraglide upgrade to v2
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/project.inlang/project_id
  frontend/project.inlang/settings.json
  frontend/src/hooks.server.ts
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/ModelTable/ModelTable.svelte
  frontend/src/lib/components/SideBar/SideBarFooter.svelte
  frontend/src/params/lang.ts
  frontend/src/routes/(app)/(internal)/loaded-libraries/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/my-assignments/+page.svelte
  frontend/src/routes/(app)/(internal)/my-assignments/AuditCard.svelte
  frontend/src/routes/(app)/(internal)/my-profile/+page.svelte
  frontend/src/routes/(app)/(internal)/risk-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/stored-libraries/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/+layout.server.ts
  frontend/src/routes/(authentication)/login/+page.server.ts
  frontend/src/routes/(authentication)/password-reset/confirm/+page.server.ts
  frontend/src/routes/+layout.server.ts
  frontend/src/routes/ParaglideJsProvider.svelte
  frontend/tests/functional/nav.test.ts
  frontend/vite.config.ts
Labels: dependencies, High Value

#1708 fix: add ref_id field for FindingsAssessment model
  backend/core/migrations/0061_findingsassessment_ref_id.py
  backend/core/models.py
  backend/core/serializers.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/utils/table.ts
Labels: data-model

#1718 feat(lib): add CIS benchmark for Kubernetes hardening
  backend/library/libraries/cis-benchmark-kubernetes.yaml
  tools/cis/cis-benchmark-kubernetes.xlsx
Labels: Framework

#1704 feat(lib): add Google SAIF framework
  backend/library/libraries/google-saif.yaml
  tools/convert_library.py
  tools/google/google-saif.xlsx
Labels: Framework

#1578 feat: add labels for threats, reference controls and applied controls
  backend/core/migrations/0062_appliedcontrol_filtering_labels_and_more.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/views.py
  frontend/src/lib/components/Forms/AutocompleteSelect.svelte
  frontend/src/lib/components/Forms/ModelForm/AppliedControlPolicyForm.svelte
  frontend/src/lib/components/Forms/ModelForm/ReferenceControlForm.svelte
  frontend/src/lib/components/Forms/ModelForm/ThreatForm.svelte
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
Labels: data-model

#1609 fix: properly reflect role permissions in the UI
  backend/iam/models.py
  backend/iam/views.py
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/ModelTable/ModelTable.svelte
  frontend/src/lib/components/TableRowActions/TableRowActions.svelte
  frontend/src/lib/utils/access-control.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/my-profile/+page.svelte
  frontend/src/routes/(app)/(internal)/risk-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/risk-scenarios/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(third-party)/compliance-assessments/[id=uuid]/+page.svelte
Labels: UX

#1770 doc: update readme
  README.md
Labels: documentation

#1767 feat: link assets to applied controls
  backend/core/migrations/0063_appliedcontrol_assets.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/views.py
  frontend/src/lib/components/Forms/ModelForm/AppliedControlPolicyForm.svelte
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/schemas.ts
Labels: data-model

#1719 feat: implement major incidents management
  backend/core/migrations/0064_incident_timelineentry.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/startup.py
  backend/core/urls.py
  backend/core/views.py
  documentation/architecture/data-model.md
  enterprise/frontend/src/lib/components/SideBar/navData.ts
  frontend/messages/ar.json
  frontend/messages/cs.json
  frontend/messages/de.json
  frontend/messages/en.json
  frontend/messages/es.json
  frontend/messages/fr.json
  frontend/messages/hi.json
  frontend/messages/id.json
  frontend/messages/it.json
  frontend/messages/nl.json
  frontend/messages/pl.json
  frontend/messages/pt.json
  frontend/messages/ro.json
  frontend/messages/sv.json
  frontend/messages/ur.json
  frontend/src/lib/components/DetailView/DetailView.svelte
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/IncidentForm.svelte
  frontend/src/lib/components/Forms/ModelForm/TimelineEntryForm.svelte
  frontend/src/lib/components/Forms/TextField.svelte
  frontend/src/lib/components/ModelTable/ModelTable.svelte
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/lib/utils/actions.ts
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/i18n.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
Labels: new feature, data-model

#1760 prevent / in domain and perimeter name
  backend/core/migrations/0064_replace_slash_in_folder_names.py
  backend/core/serializers.py
  backend/iam/migrations/0011_replace_slash_in_folder_names.py
Labels: data-model

#1721 feat: GDPR Processings register
  backend/ciso_assistant/settings.py
  backend/core/constants.py
  backend/core/startup.py
  backend/core/urls.py
  backend/privacy/__init__.py
  backend/privacy/admin.py
  backend/privacy/apps.py
  backend/privacy/migrations/0001_initial.py
  backend/privacy/migrations/__init__.py
  backend/privacy/models.py
  backend/privacy/serializers.py
  backend/privacy/tests.py
  backend/privacy/urls.py
  backend/privacy/views.py
  enterprise/backend/enterprise_core/settings.py
  enterprise/frontend/src/lib/components/SideBar/navData.ts
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/Chart/TreemapChart.svelte
  frontend/src/lib/components/DataViz/WorldMap.svelte
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/DataContractorForm.svelte
  frontend/src/lib/components/Forms/ModelForm/DataRecipientForm.svelte
  frontend/src/lib/components/Forms/ModelForm/DataSubjectForm.svelte
  frontend/src/lib/components/Forms/ModelForm/DataTransferForm.svelte
  frontend/src/lib/components/Forms/ModelForm/PersonalDataForm.svelte
  frontend/src/lib/components/Forms/ModelForm/ProcessingForm.svelte
  frontend/src/lib/components/Forms/ModelForm/PurposeForm.svelte
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/load.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/analytics/gdpr/+page.server.ts
  frontend/src/routes/(app)/(internal)/analytics/gdpr/+page.svelte
  frontend/src/routes/(app)/(internal)/analytics/gdpr/Card.svelte
  frontend/src/routes/(app)/(internal)/processings/[id=uuid]/+page.server.ts
  frontend/src/routes/(app)/(internal)/processings/[id=uuid]/+page.svelte
Labels: data-model
