Repository intuitem/ciso-assistant-community, pull requests merged in 2025-09, with the labels that each got.

#2392 test(enterprise): functional tests for client settings module
  .github/workflows/functional-tests.yml
  enterprise/frontend/Makefile
  enterprise/frontend/src/lib/components/Logo/Logo.svelte
  enterprise/frontend/src/routes/(app)/(internal)/settings/client-settings/+page.svelte
  frontend/.gitignore
  frontend/src/lib/components/Logo/Logo.svelte
  frontend/tests/e2e-tests.sh
  frontend/tests/functional/enterprise/settings/client.test.ts
  frontend/tests/utils/sidebar.ts
  frontend/tests/utils/test-data.ts
  frontend/tests/utils/test_favicon.ico
  frontend/tests/utils/test_image.jpg
  frontend/tests/utils/test_image.png
  frontend/tests/utils/test_logo.png
Labels: pro, tests

#2483 chores: frontend dependencies upgrade
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: dependencies

#2552 feat: export findings data (excel, pdf, md)
  backend/core/templates/core/base_pdf.html
  backend/core/templates/core/findings_assessment_pdf.html
  backend/core/views.py
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/routes/(app)/(internal)/findings-assessments/[id=uuid]/+page.svelte
  frontend/src/routes/(app)/(internal)/findings-assessments/[id=uuid]/export/md/+server.ts
  frontend/src/routes/(app)/(internal)/findings-assessments/[id=uuid]/export/pdf/+server.ts
  frontend/src/routes/(app)/(internal)/findings-assessments/[id=uuid]/export/xlsx/+server.ts
  reformat.sh
Labels: High Value

#2586 fix(lib): GDPR Framework Fix & in Swedish (SV) + fix(tool): Update convert_library_v2.py
  backend/library/libraries/gdpr.yaml
  tools/README.md
  tools/convert_library_v2.py
  tools/excel/gdpr/GDPR.xlsx
Labels: Framework, translation, toolbox

#2602 feat: managing GDPR rights requests
  backend/core/startup.py
  backend/privacy/migrations/0007_rightrequest.py
  backend/privacy/models.py
  backend/privacy/serializers.py
  backend/privacy/urls.py
  backend/privacy/views.py
  enterprise/frontend/src/lib/components/SideBar/navData.ts
  frontend/messages/en.json
  frontend/messages/fr.json
  frontend/src/lib/components/Forms/ModelForm.svelte
  frontend/src/lib/components/Forms/ModelForm/RightRequestForm.svelte
  frontend/src/lib/components/SideBar/navData.ts
  frontend/src/lib/utils/crud.ts
  frontend/src/lib/utils/schemas.ts
  frontend/src/lib/utils/table.ts
  frontend/src/lib/utils/types.ts
  frontend/src/routes/(app)/(internal)/analytics/gdpr/+page.svelte
Labels: db-migration
